
PRUNING_DEFAULT_CONFIG = {
    "profile_iterations": 100,
    "num_workers": 4,
    "test_batch_size": 128,
    "test_image_side": 224,
    "prune_image_side": None,
    "methods_for_classes": {
        # "Unstructured": {
        #     "Magnitude": [
        #         "Rand", 
        #         "L1", 
        #     ],
        # },
        # "Structured": {
        #     "Magnitude": [
        #         "Rand", 
        #         "L1", 
        #         "L2", 
        #     ],
        # },
        "StructuredConsistent": {
            # "Magnitude": [
            #     # "Rand", 
            #     # "L1", 
            #     # "L2", 
            #     # "Efficiency(0.25x)",
            #     # "Efficiency(0.5x)",
            #     # "Efficiency(0.75x)",
            #     # "Efficiency(1x)",
            #     # "EfficiencyGPU(0.25x)",
            #     # "EfficiencyGPU(0.5x)",
            #     # "EfficiencyGPU(0.75x)",
            #     # "EfficiencyGPU(1x)",
            #     # "Union-L2-Efficiency",
            #     # "Taylor",
            #     # "LAMP",
            #     # "FPGM",
            # ],
            # "BNScale": [
            #     "BNScale", 
            # ],
            # "BNScaleLasso": [
            #     "BNScale", 
            # ],
            "GroupNorm": [
                # "StaticNormL2",
                "L2", 
                # "Efficiency",
                # "L2MaxNorm",
                # "Efficiency(1x)",
                # "Efficiency(2x)",
                # "Efficiency(3x)",
                # "EfficiencyThr95",
                # "EfficiencyThr90",
                # "EfficiencyThr80",
                # "EfficiencyThr70",
                # "EfficiencyGPU(1x)",
                # "EfficiencyGPU(2x)",
                # "EfficiencyGPU(3x)",
                # "EfficiencyGPU",
                # "EfficiencyOnLayer(1x)",
                # "EfficiencyOnLayer(2x)",
                # "EfficiencyOnLayer(3x)",
                # "EfficiencyOnLayer",
                # "EfficiencyGPUOnLayer(1x)",
                # "EfficiencyGPUOnLayer(2x)",
                # "EfficiencyGPUOnLayer(3x)",
                # "EfficiencyGPUOnLayer",
            ],
            "GroupProf": [
                "L2",
            ],
            # "GroupNormReg": [
            #     "L2MaxNorm",
            # ],
            # "GroupEfficiency": [
            #     # "StaticNormL2",
            #     # "L2", 
            #     # "Efficiency(1x)",
            #     # "Efficiency(2x)",
            #     # "Efficiency(3x)",
            #     # "Efficiency",
            #     "EfficiencyMaxNorm",
            #     "EfficiencyMaxNormThr95",
            #     "EfficiencyMaxNormThr90",
            #     "EfficiencyMaxNormThr80",
            #     "EfficiencyMaxNormThr70",
            #     # "EfficiencyGPU(1x)",
            #     # "EfficiencyGPU(2x)",
            #     # "EfficiencyGPU(3x)",
            #     # "EfficiencyGPU",
            #     # "EfficiencyOnLayer(1x)",
            #     # "EfficiencyOnLayer(2x)",
            #     # "EfficiencyOnLayer(3x)",
            #     # "EfficiencyOnLayer",
            #     # "EfficiencyGPUOnLayer(1x)",
            #     # "EfficiencyGPUOnLayer(2x)",
            #     # "EfficiencyGPUOnLayer(3x)",
            #     # "EfficiencyGPUOnLayer",
            # ],
            # "GrowingReg": [
            #     "L2",
            #     "Efficiency(1x)",
            #     "Efficiency(2x)",
            #     "Efficiency(3x)",
            #     "Efficiency",
            #     "EfficiencyGPU(1x)",
            #     "EfficiencyGPU(2x)",
            #     "EfficiencyGPU(3x)",
            #     "EfficiencyGPU",
            # ],
        }
    },
    "percs": [
        # {
        #     "resnet18": "2.8x",
        #     "resnet56": "3.1x",
        #     "vgg11": "2.4x",
        #     "densenet121": "2.6x",
        #     "vgg19": "2.4x",
        # },
        # {
        #     "resnet18": "4.2x",
        #     "resnet56": "4.1x",
        #     "vgg11": "3.6x",
        #     "densenet121": "3.8x",
        #     "vgg19": "3.7x",
        # },
        # {
        #     "resnet18": "7.0x",
        #     "resnet56": "6.9x",
        #     # "resnet56": "2.55x",
        #     "vgg11": "6.0x",
        #     "densenet121": "6.2x",
        #     # "vgg19": "6.2x",
        #     "vgg19": "8.84x",
        # },
        # 0.1, # 0.15, 
        # 0.2, # 0.25, 
        # 0.3, # 0.35, 
        # 0.4, # 0.45, 
        # 0.5, # 0.55, 
        # 0.6, # 0.65, 
        # 0.7, # 0.75, 
        # 0.8, # 0.85, 
        # 0.9, 
        # {
        #     "resnet18": "2.0x",
        #     "resnet56": "1.5x",
        #     "vgg11": "2.0x",
        #     "densenet121": "2.0x",
        #     "vgg19": "2.0x",
        # },
        # {
        #     "GroupNorm": {
        #         "resnet18": 0,
        #         "resnet56": 0,
        #         "vgg11": 0,
        #         "densenet121": 0,
        #         "vgg19": 87,
        #     },
        #     "GroupProf": {
        #         "resnet18": 0,
        #         "resnet56": 0,
        #         "vgg11": 0,
        #         "densenet121": 0,
        #         "vgg19": 98,
        #     },
        # },
        "1.5x",
        "2.0x",
        # "2.5x",
    ],
    "list_of_steps": [
        1,
    ],
    "global": [
        # False, 
        True,
    ],
    "test_subset": [
        # 1, 
        # 10,
        # 20, 
        # 50, 
        # 100,
        # 0.1,
        # 0.2,
        # 0.4,
        # 0.6,
        # 0.8,
        None,
    ],
    "group_selection": {
        "methods": [
            None, 
            # "Rand", 
            # "Efficiency",
            # "Performance",
            # "L2",
            # "MinIntersection",
            # "Similarity",
            # "DiffSpread",
            # "Spread"
        ],
        "percs": [
            # "auto",
            # 0.1,
            # 0.2,
            # 0.3, 
            # 0.4,
            0.5,
            0.55,
            0.6,
            0.65,
            0.7,
            0.75,
            0.8,
            0.85,
            0.9,
            0.95,
        ]
    }
}